import java.io.File
import java.nio.file.Files
import java.util.*
import static de.tobiasroeser.lambdatest.Expect.*

expectEquals(
  basedir.listFiles().collect { it.getName() }.toSet(), 
  ["build.log", "pom.xml", "verify.groovy", ".project", ".settings"].toSet()
)

settingsdir = new File(basedir, ".settings")

expectEquals(
  settingsdir.listFiles().collect { it.getName() }.toSet(),
  ["org.eclipse.core.resources.prefs", "org.eclipse.m2e.core.prefs"].toSet()
)
  
expectEquals(
  Files.readAllLines(new File(basedir , ".project").toPath()).join("\n"),
  """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by eclipse-maven-plugin -->
<projectDescription>
	<name>project name</name>
	<comment>project description</comment>
	<projects>
	</projects>
	<buildSpec>
		<buildCommand>
			<name>org.eclipse.m2e.core.maven2Builder</name>
			<arguments>
			</arguments>
		</buildCommand>
	</buildSpec>
	<natures>
		<nature>org.eclipse.m2e.core.maven2Nature</nature>
	</natures>
</projectDescription>"""
)

expectEquals(
  Files.readAllLines(new File(settingsdir, "org.eclipse.m2e.core.prefs").toPath()).join("\n"),
  """activeProfiles=
eclipse.preferences.version=1
resolveWorkspaceProjects=true
version=1"""
)

expectEquals(
  Files.readAllLines(new File(settingsdir, "org.eclipse.core.resources.prefs").toPath()).join("\n"),
  """eclipse.preferences.version=1
encoding//src/main/java=UTF-8
encoding//src/main/resources=UTF-8
encoding//src/test/java=UTF-8
encoding//src/test/resources=UTF-8
encoding/<project>=UTF-8"""
)

